name: affirmation
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.3
  
  # Storage & Sharing
  share_plus: ^10.0.3
  shared_preferences: ^2.3.3
  
  # Web Support
  universal_html: ^2.2.4
  
  # Monetization
  in_app_purchase: ^3.2.2
  
  # Audio & Media
  audioplayers: ^6.1.0
  flutter_tts: ^4.2.0
  video_player: ^2.8.2
  
  # Notifications & timezone 
  awesome_notifications: ^0.10.1
  timezone: ^0.9.4

  # UI
  cupertino_icons: ^1.0.8
  
  # Code Generation
  flutter_gen: ^5.12.0

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  flutter_local_notifications: ^17.2.3

  confetti: ^0.7.0

  permission_handler: ^11.3.1  # En g√ºncel versiyon


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    # Theme Data
    - assets/data/themes/themes.json
    
    # English Categories & Content
    - assets/data/en/categories.json
    - assets/data/en/general.json
    - assets/data/en/self_care.json
    - assets/data/en/stress_anxiety.json
    - assets/data/en/positive_thinking.json
    - assets/data/en/motivation.json
    - assets/data/en/happiness.json
    - assets/data/en/relationships.json
    - assets/data/en/confidence.json
    - assets/data/en/mindfulness.json
    - assets/data/en/gratitude.json
    - assets/data/en/career_success.json
    - assets/data/en/sleep.json
    
    # Turkish Categories & Content
    - assets/data/tr/self_care.json
    - assets/data/tr/stress_anxiety.json
    - assets/data/tr/positive_thinking.json
    - assets/data/tr/motivation.json
    - assets/data/tr/healing.json
    - assets/data/tr/happiness.json
    - assets/data/tr/relationships.json
    - assets/data/tr/confidence.json
    - assets/data/tr/mindfulness.json
    - assets/data/tr/gratitude.json
    - assets/data/tr/career_success.json
    - assets/data/tr/sleep.json
    
    # Spanish Categories & Content
    - assets/data/es/self_care.json
    - assets/data/es/stress_anxiety.json
    - assets/data/es/positive_thinking.json
    - assets/data/es/body_positivity.json
    - assets/data/es/focus_productivity.json
    - assets/data/es/motivation.json
    - assets/data/es/healing.json
    - assets/data/es/happiness.json
    - assets/data/es/relationships.json
    - assets/data/es/confidence.json
    - assets/data/es/mindfulness.json
    - assets/data/es/gratitude.json
    - assets/data/es/law_of_attraction.json
    - assets/data/es/spirituality.json
    - assets/data/es/inner_child.json
    - assets/data/es/career_success.json
    - assets/data/es/sleep.json
    
    # Theme Images
    - assets/data/themes/a1.jpg
    - assets/data/themes/a2.jpg
    - assets/data/themes/a3.jpg
    - assets/data/themes/a4.jpg
    - assets/data/themes/a5.jpg
    - assets/data/themes/a6.jpg
    - assets/data/themes/a7.jpg
    - assets/data/themes/a8.jpg
    - assets/data/themes/a9.jpg
    - assets/data/themes/a10.jpg

    - assets/data/themes/c1.jpg
    - assets/data/themes/c2.jpg
    - assets/data/themes/c3.jpg
    - assets/data/themes/c4.jpg
    - assets/data/themes/c5.jpg
    - assets/data/themes/c6.jpg
    - assets/data/themes/c7.jpg
    - assets/data/themes/c8.jpg
    - assets/data/themes/c9.jpg
    - assets/data/themes/c10.jpg
    - assets/data/themes/c11.jpg
    - assets/data/themes/c12.jpg
    - assets/data/themes/c13.jpg
    - assets/data/themes/c14.jpg
    - assets/data/themes/c15.jpg

    - assets/data/themes/d1.jpg
    - assets/data/themes/d2.jpg
    - assets/data/themes/d3.jpg
    - assets/data/themes/d4.jpg
    - assets/data/themes/d5.jpg
    - assets/data/themes/d6.jpg
    - assets/data/themes/d7.jpg
    - assets/data/themes/d8.jpg
    - assets/data/themes/d9.jpg
    - assets/data/themes/e1.mp4
    
    # Category Images
    - assets/data/categories/career.jpg
    - assets/data/categories/favorites.jpg
    - assets/data/categories/mindfulness.jpg
    - assets/data/categories/motivation.jpg
    - assets/data/categories/selfcare.jpg
    - assets/data/categories/sleep.jpg
    - assets/data/categories/stress.jpg
    - assets/data/categories/relationships.jpg
    - assets/data/categories/positive.jpg
    - assets/data/categories/general.jpg
    - assets/data/categories/gratitude.jpg
    - assets/data/categories/myAffirmations.jpg
    - assets/data/categories/happiness.jpg
    - assets/data/categories/confidence.jpg
    - assets/data/categories/background.jpg

# Localization Configuration
flutter_gen:
  output: lib/gen/
  line_length: 80

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false